import type { BlockVariant, PromptTemplate } from "./types";
import { applyBlockCriteria } from "./block-criteria";

/** Блоки — переиспользуемые части. Часть общая между промтами, часть уникальна. */
const RAW_MOCK_BLOCKS: BlockVariant[] = [
  // ── ROLE ──
  {
    id: "role_shorts_writer",
    kind: "role",
    label: "Сценарист shorts",
    tags: ["shorts", "vertical"],
    steps: ["plan", "script"],
    sharedCount: 4,
    body: "Ты — сценарист коротких вертикальных роликов. Пишешь плотно, без воды, под озвучку.",
  },
  {
    id: "role_xlsx_agent",
    kind: "role",
    label: "Excel-агент",
    tags: ["excel", "enrich"],
    steps: ["enrich_1", "enrich_2", "enrich_3"],
    sharedCount: 5,
    body: "Ты — агент заполнения Excel-таблицы. Работаешь построчно, не дублируешь сущности.",
  },
  {
    id: "role_image_prompter",
    kind: "role",
    label: "Image prompt engineer",
    tags: ["image", "visual"],
    steps: ["img_pr", "hero"],
    sharedCount: 3,
    body: "Ты — инженер image prompts для генерации кадров. Фиксируешь стиль, не сюжет из примера.",
  },
  {
    id: "role_plan_architect",
    kind: "role",
    label: "Архитектор плана",
    tags: ["plan"],
    steps: ["plan"],
    body: "Собирает общий план ролика с таймингами и героями.",
  },
  {
    id: "role_animation_director",
    kind: "role",
    label: "Режиссёр анимации",
    tags: ["animation"],
    steps: ["anim_pr"],
    body: "Описывает движение камеры и объектов в animation prompt.",
  },
  {
    id: "role_hero_designer",
    kind: "role",
    label: "Дизайнер героя",
    tags: ["hero"],
    steps: ["hero"],
    body: "Канон персонажа для hero sheet и кадров.",
  },
  {
    id: "role_enrich_orchestrator",
    kind: "role",
    label: "Enrich-оркестратор",
    tags: ["enrich"],
    steps: ["enrich_1", "enrich_2"],
    body: "Координирует цепочку enrich и целостность таблицы.",
  },
  {
    id: "role_qa_reviewer",
    kind: "role",
    label: "QA / Review",
    tags: ["check"],
    steps: ["plan", "script", "img_pr"],
    body: "Проверяет скелет промта перед отправкой в GPT.",
  },

  // ── TECHNICAL ──
  {
    id: "tech_60sec_vertical",
    kind: "technical",
    label: "60 сек · 9:16",
    tags: ["shorts", "timing"],
    steps: ["plan", "script", "split"],
    sharedCount: 6,
    body: "Длительность: {{VIDEO_DURATION_SEC}} сек. Формат: вертикаль 9:16. Блоки по {{FRAME_DURATION_MIN_SEC}}–{{FRAME_DURATION_MAX_SEC}} сек.",
  },
  {
    id: "tech_voiceover_chars",
    kind: "technical",
    label: "Объём озвучки 800–900",
    tags: ["voiceover"],
    steps: ["plan", "script"],
    sharedCount: 3,
    body: "Целевой объём закадрового текста: {{VOICEOVER_MIN_CHARS}}–{{VOICEOVER_MAX_CHARS}} знаков без пробелов.",
  },
  {
    id: "tech_xlsx_row52",
    kind: "technical",
    label: "XLSX Agent V7.2 Row52",
    tags: ["excel", "v7"],
    steps: ["enrich_1"],
    sharedCount: 1,
    body: "Заполняй только колонки плана. Строка 52 — усиленные правила связности между блоками. Не трогай image_prompt.",
  },
  {
    id: "tech_image_len",
    kind: "technical",
    label: "Длина image prompt 500–4800",
    tags: ["image"],
    steps: ["img_pr", "hero"],
    sharedCount: 2,
    body: "Длина каждого image prompt: {{PROMPT_LEN_MIN}}–{{PROMPT_LEN_MAX}} символов. Один кадр — один промт.",
  },
  {
    id: "tech_anim_8sec",
    kind: "technical",
    label: "Анимация до 8 сек",
    tags: ["animation"],
    steps: ["anim_pr"],
    sharedCount: 1,
    body: "Длительность клипа: до {{VIDEO_DURATION_MAX_SEC}} сек. Описывай движение камеры и объекта, не сюжет заново.",
  },

  // ── FEATURES (стили — частично общие между hero и image) ──
  {
    id: "feat_pixelart_cinematic",
    kind: "features",
    label: "Cinematic pixel art",
    tags: ["pixelart", "cats"],
    steps: ["hero", "img_pr", "anim_pr"],
    sharedCount: 3,
    body: "Mature cinematic pixel art: ultra detailed, subpixel shading, soft dithering. Не retro 8-bit, не photorealism, не anime.",
  },
  {
    id: "feat_knitted_2d",
    kind: "features",
    label: "Вязаный 2D стиль",
    tags: ["textile", "handmade"],
    steps: ["hero", "img_pr"],
    sharedCount: 2,
    body: "Textile cut-paper illustration: felt texture, embroidered fabric, warm autumn palette, stylized flat shapes, children's book warmth.",
  },
  {
    id: "feat_clay_plasticine",
    kind: "features",
    label: "Пластилин",
    tags: ["clay", "3d-feel"],
    steps: ["img_pr"],
    sharedCount: 1,
    body: "Plasticine stop-motion aesthetic: visible fingerprints, soft clay lumps, handmade imperfections, warm studio lighting.",
  },
  {
    id: "feat_trash_polka",
    kind: "features",
    label: "Trash polka / noir comic",
    tags: ["dark", "comic"],
    steps: ["hero", "img_pr"],
    sharedCount: 2,
    body: "Trash polka noir comic: high contrast red/black, ink splatter, graphic novel framing, gritty texture, dramatic shadows.",
  },
  {
    id: "feat_dark_bloody",
    kind: "features",
    label: "Дарк грязный кровавый",
    tags: ["dark", "horror"],
    steps: ["img_pr"],
    sharedCount: 1,
    body: "Dark dirty bloody aesthetic: desaturated greens, rust, dried blood accents, grimy surfaces, unsettling mood.",
  },
  {
    id: "feat_camera_slow_push",
    kind: "features",
    label: "Камера: slow push-in",
    tags: ["camera"],
    steps: ["anim_pr", "img_pr"],
    sharedCount: 2,
    body: "Camera: slow push-in, medium/full mix framing, isolated subject, no busy background.",
  },
  {
    id: "feat_anthro_cats",
    kind: "features",
    label: "Антропоморфные коты",
    tags: ["cats", "world"],
    steps: ["plan", "hero", "img_pr"],
    sharedCount: 4,
    body: "World: anthropomorphic cats, mature proportions, expressive faces, no humans in frame.",
  },

  // ── RULES ──
  {
    id: "rules_anti_doubles",
    kind: "rules",
    label: "ANTI-DUBLES",
    tags: ["excel", "enrich"],
    steps: ["enrich_1", "enrich_5"],
    sharedCount: 2,
    body: "Запрещено дублировать персонажей, локации и реквизит между строками. Каждая строка — уникальный визуальный блок.",
  },
  {
    id: "rules_table_v7",
    kind: "rules",
    label: "Правило заполнения V7",
    tags: ["excel"],
    steps: ["enrich_1"],
    sharedCount: 1,
    body: "Заполняй plan-колонки строго по шаблону V7. Не выдумывай столбцы. Связность block_id обязательна.",
  },
  {
    id: "rules_no_style_mix",
    kind: "rules",
    label: "Не смешивать стили",
    tags: ["image"],
    steps: ["img_pr", "hero"],
    sharedCount: 3,
    body: "STYLE_LOCK: не смешивать photorealistic humans, anime, glossy 3D, cold digital realism с текущим стилем.",
  },
  {
    id: "rules_ai_cliches_ru",
    kind: "rules",
    label: "Запрет AI-клише RU",
    tags: ["text"],
    steps: ["plan", "script", "img_pr"],
    sharedCount: 5,
    body: "Не используй: «в современном мире», «давайте погрузимся», «уникальный», «революционный», канцелярит.",
  },
  {
    id: "rules_character_agent",
    kind: "rules",
    label: "Агент персонажей",
    tags: ["enrich"],
    steps: ["enrich_2"],
    sharedCount: 1,
    body: "Создавай только описания персонажей для hero_sheet. Не пиши image_prompt и не меняй plan.",
  },

  // ── NARRATIVE ──
  {
    id: "narr_hook_insight",
    kind: "narrative",
    label: "Hook → insight (shorts)",
    tags: ["shorts"],
    steps: ["plan", "script"],
    sharedCount: 3,
    body: "Структура: сильный hook 0–3 сек → нарастание → insight/поворот → финальный punch.",
  },
  {
    id: "narr_detective",
    kind: "narrative",
    label: "Детективный шаблон",
    tags: ["detective"],
    steps: ["plan"],
    sharedCount: 1,
    body: "Жанр: детективная мини-история. Загадка в начале, улики по ходу, развязка в финале.",
  },
  {
    id: "narr_documentary_calm",
    kind: "narrative",
    label: "Документальный спокойный тон",
    tags: ["tone"],
    steps: ["plan", "script"],
    sharedCount: 4,
    body: "Тон: спокойный документальный закадр. Без крика, без хайпа, факты и образы.",
  },
  {
    id: "narr_steven_king",
    kind: "narrative",
    label: "Стивен Кинг (атмосфера)",
    tags: ["horror", "story"],
    steps: ["script"],
    sharedCount: 1,
    body: "Атмосфера everyday horror: обыденность + тревога, медленное нагнетание, детали быта.",
  },

  // ── NEGATIVE ──
  {
    id: "neg_no_text_logos",
    kind: "negative",
    label: "No text / logos",
    tags: ["image"],
    steps: ["img_pr", "hero", "anim_pr"],
    sharedCount: 4,
    body: "Negative: text, watermark, logo, border, UI elements, subtitles.",
  },
  {
    id: "neg_no_humans",
    kind: "negative",
    label: "No humans",
    tags: ["cats"],
    steps: ["img_pr", "hero"],
    sharedCount: 2,
    body: "Negative: humans, realistic faces, photorealistic skin, extra fingers.",
  },

  // ── OUTPUT ──
  {
    id: "out_plan_timeline",
    kind: "output",
    label: "План с таймингами",
    tags: ["plan"],
    steps: ["plan"],
    sharedCount: 1,
    body: "Верни markdown: ## Блоки с таймингами, ## Герои, ## Визуальные акценты. Без лишних комментариев.",
  },
  {
    id: "out_script_voiceover",
    kind: "output",
    label: "Сценарий озвучки",
    tags: ["script"],
    steps: ["script"],
    sharedCount: 2,
    body: "Верни чистый текст закадрового голоса, абзацы = блоки. Без stage directions.",
  },
  {
    id: "out_image_prompt_template",
    kind: "output",
    label: "Шаблон image prompt v2.2",
    tags: ["image"],
    steps: ["img_pr"],
    sharedCount: 1,
    body: "Формат: СТИЛЬ → PROMPT (EN) → NEGATIVE PROMPT. Переменные в [CAPS]. Не копируй пример-сюжет.",
  },
  {
    id: "out_excel_json",
    kind: "output",
    label: "Excel JSON patch",
    tags: ["excel"],
    steps: ["enrich_1", "enrich_2"],
    sharedCount: 2,
    body: "Верни только JSON-массив изменённых ячеек: [{row, col, value}]. Без пояснений.",
  },
];

export const MOCK_BLOCKS = applyBlockCriteria(RAW_MOCK_BLOCKS);

export const MOCK_TEMPLATES: PromptTemplate[] = [
  {
    id: "tpl_plan_detective",
    stepCode: "plan",
    label: "План · детектив",
    category: "01_plan",
    description: "01_shablon_detektiv — насыщенный план shorts",
    legacyFile: "01_shablon_detektiv.txt.md",
    hasAccompanying: true,
    slots: [
      { slotId: "role", kind: "role", required: true, defaultBlockId: "role_shorts_writer" },
      { slotId: "tech_duration", kind: "technical", required: true, defaultBlockId: "tech_60sec_vertical" },
      { slotId: "tech_chars", kind: "technical", required: false, defaultBlockId: "tech_voiceover_chars" },
      { slotId: "narr_genre", kind: "narrative", required: true, defaultBlockId: "narr_detective" },
      { slotId: "narr_tone", kind: "narrative", required: true, defaultBlockId: "narr_documentary_calm" },
      { slotId: "feat_world", kind: "features", required: false, defaultBlockId: "feat_anthro_cats" },
      { slotId: "rules_cliches", kind: "rules", required: true, defaultBlockId: "rules_ai_cliches_ru" },
      { slotId: "output", kind: "output", required: true, defaultBlockId: "out_plan_timeline" },
    ],
  },
  {
    id: "tpl_plan_food",
    stepCode: "plan",
    label: "План · food story",
    category: "01_plan",
    legacyFile: "04_shablon_food_story.txt.md",
    slots: [
      { slotId: "role", kind: "role", required: true, defaultBlockId: "role_shorts_writer" },
      { slotId: "tech", kind: "technical", required: true, defaultBlockId: "tech_60sec_vertical" },
      { slotId: "narr", kind: "narrative", required: true, defaultBlockId: "narr_hook_insight" },
      { slotId: "rules", kind: "rules", required: true, defaultBlockId: "rules_ai_cliches_ru" },
      { slotId: "output", kind: "output", required: true, defaultBlockId: "out_plan_timeline" },
    ],
  },
  {
    id: "tpl_script_default",
    stepCode: "script",
    label: "Сценарий · default",
    category: "02_script",
    legacyFile: "default.md",
    hasAccompanying: true,
    slots: [
      { slotId: "role", kind: "role", required: true, defaultBlockId: "role_shorts_writer" },
      { slotId: "tech", kind: "technical", required: true, defaultBlockId: "tech_voiceover_chars" },
      { slotId: "narr_structure", kind: "narrative", required: true, defaultBlockId: "narr_hook_insight" },
      { slotId: "narr_tone", kind: "narrative", required: true, defaultBlockId: "narr_documentary_calm" },
      { slotId: "rules", kind: "rules", required: true, defaultBlockId: "rules_ai_cliches_ru" },
      { slotId: "output", kind: "output", required: true, defaultBlockId: "out_script_voiceover" },
    ],
  },
  {
    id: "tpl_script_king",
    stepCode: "script",
    label: "Сценарий · Стивен Кинг",
    category: "02_script",
    legacyFile: "стивен кинг.txt.md",
    slots: [
      { slotId: "role", kind: "role", required: true, defaultBlockId: "role_shorts_writer" },
      { slotId: "tech", kind: "technical", required: true, defaultBlockId: "tech_voiceover_chars" },
      { slotId: "narr", kind: "narrative", required: true, defaultBlockId: "narr_steven_king" },
      { slotId: "rules", kind: "rules", required: true, defaultBlockId: "rules_ai_cliches_ru" },
      { slotId: "output", kind: "output", required: true, defaultBlockId: "out_script_voiceover" },
    ],
  },
  {
    id: "tpl_enrich1_v7",
    stepCode: "enrich_1",
    label: "Enrich 1 · XLSX V7.2",
    category: "05a_enrich_1",
    legacyFile: "XLSX_Agent_V7_2_Row52_Strengthened.txt.md",
    hasAccompanying: true,
    slots: [
      { slotId: "role", kind: "role", required: true, defaultBlockId: "role_xlsx_agent" },
      { slotId: "tech", kind: "technical", required: true, defaultBlockId: "tech_xlsx_row52" },
      { slotId: "rules_table", kind: "rules", required: true, defaultBlockId: "rules_table_v7" },
      { slotId: "rules_doubles", kind: "rules", required: true, defaultBlockId: "rules_anti_doubles" },
      { slotId: "output", kind: "output", required: true, defaultBlockId: "out_excel_json" },
    ],
  },
  {
    id: "tpl_enrich2_chars",
    stepCode: "enrich_2",
    label: "Enrich 2 · Персонажи",
    category: "05b_enrich_2",
    legacyFile: "агент по созданию персонажей.txt.md",
    slots: [
      { slotId: "role", kind: "role", required: true, defaultBlockId: "role_xlsx_agent" },
      { slotId: "rules", kind: "rules", required: true, defaultBlockId: "rules_character_agent" },
      { slotId: "output", kind: "output", required: true, defaultBlockId: "out_excel_json" },
    ],
  },
  {
    id: "tpl_img_knitted",
    stepCode: "img_pr",
    label: "Image · вязаный 2D",
    category: "05_image_prompts",
    legacyFile: "вязаный 2д стиль.txt.md",
    hasAccompanying: true,
    slots: [
      { slotId: "role", kind: "role", required: true, defaultBlockId: "role_image_prompter" },
      { slotId: "tech", kind: "technical", required: true, defaultBlockId: "tech_image_len" },
      { slotId: "feat_style", kind: "features", required: true, defaultBlockId: "feat_knitted_2d" },
      { slotId: "rules", kind: "rules", required: true, defaultBlockId: "rules_no_style_mix" },
      { slotId: "neg", kind: "negative", required: true, defaultBlockId: "neg_no_text_logos" },
      { slotId: "output", kind: "output", required: true, defaultBlockId: "out_image_prompt_template" },
    ],
  },
  {
    id: "tpl_img_trash_polka",
    stepCode: "img_pr",
    label: "Image · trash polka",
    category: "05_image_prompts",
    legacyFile: "trash_polka_noir_comic_prompt_template_v2.txt.md",
    slots: [
      { slotId: "role", kind: "role", required: true, defaultBlockId: "role_image_prompter" },
      { slotId: "tech", kind: "technical", required: true, defaultBlockId: "tech_image_len" },
      { slotId: "feat_style", kind: "features", required: true, defaultBlockId: "feat_trash_polka" },
      { slotId: "rules", kind: "rules", required: true, defaultBlockId: "rules_no_style_mix" },
      { slotId: "neg", kind: "negative", required: true, defaultBlockId: "neg_no_text_logos" },
      { slotId: "output", kind: "output", required: true, defaultBlockId: "out_image_prompt_template" },
    ],
  },
  {
    id: "tpl_img_pixelart",
    stepCode: "img_pr",
    label: "Image · pixelart cats",
    category: "05_image_prompts",
    legacyFile: "default.md",
    slots: [
      { slotId: "role", kind: "role", required: true, defaultBlockId: "role_image_prompter" },
      { slotId: "tech", kind: "technical", required: true, defaultBlockId: "tech_image_len" },
      { slotId: "feat_style", kind: "features", required: true, defaultBlockId: "feat_pixelart_cinematic" },
      { slotId: "feat_world", kind: "features", required: true, defaultBlockId: "feat_anthro_cats" },
      { slotId: "feat_camera", kind: "features", required: false, defaultBlockId: "feat_camera_slow_push" },
      { slotId: "neg_humans", kind: "negative", required: true, defaultBlockId: "neg_no_humans" },
      { slotId: "neg_text", kind: "negative", required: true, defaultBlockId: "neg_no_text_logos" },
      { slotId: "output", kind: "output", required: true, defaultBlockId: "out_image_prompt_template" },
    ],
  },
  {
    id: "tpl_img_clay",
    stepCode: "img_pr",
    label: "Image · пластилин",
    category: "05_image_prompts",
    legacyFile: "пластилин.txt.md",
    slots: [
      { slotId: "role", kind: "role", required: true, defaultBlockId: "role_image_prompter" },
      { slotId: "tech", kind: "technical", required: true, defaultBlockId: "tech_image_len" },
      { slotId: "feat_style", kind: "features", required: true, defaultBlockId: "feat_clay_plasticine" },
      { slotId: "rules", kind: "rules", required: true, defaultBlockId: "rules_no_style_mix" },
      { slotId: "neg", kind: "negative", required: true, defaultBlockId: "neg_no_text_logos" },
      { slotId: "output", kind: "output", required: true, defaultBlockId: "out_image_prompt_template" },
    ],
  },
  {
    id: "tpl_hero_knitted",
    stepCode: "hero",
    label: "Hero · вязаный 2D",
    category: "04_hero",
    legacyFile: "default.md",
    slots: [
      { slotId: "role", kind: "role", required: true, defaultBlockId: "role_image_prompter" },
      { slotId: "feat_style", kind: "features", required: true, defaultBlockId: "feat_knitted_2d" },
      { slotId: "rules", kind: "rules", required: true, defaultBlockId: "rules_no_style_mix" },
      { slotId: "neg", kind: "negative", required: true, defaultBlockId: "neg_no_text_logos" },
    ],
  },
  {
    id: "tpl_anim_pixelart",
    stepCode: "anim_pr",
    label: "Animation · pixelart",
    category: "07_animation",
    legacyFile: "default.md",
    slots: [
      { slotId: "tech", kind: "technical", required: true, defaultBlockId: "tech_anim_8sec" },
      { slotId: "feat_style", kind: "features", required: true, defaultBlockId: "feat_pixelart_cinematic" },
      { slotId: "feat_camera", kind: "features", required: true, defaultBlockId: "feat_camera_slow_push" },
      { slotId: "neg", kind: "negative", required: true, defaultBlockId: "neg_no_text_logos" },
    ],
  },
];

export const MOCK_VARS: Record<string, string | number> = {
  VIDEO_DURATION_SEC: 60,
  VOICEOVER_MIN_CHARS: 800,
  VOICEOVER_MAX_CHARS: 900,
  FRAME_DURATION_MIN_SEC: 2,
  FRAME_DURATION_MAX_SEC: 4,
  PROMPT_LEN_MIN: 500,
  PROMPT_LEN_MAX: 4800,
  VIDEO_DURATION_MAX_SEC: 8,
  PROJECT_TOPIC: "Почему коты ведут себя как детективы",
};

export const MOCK_PRESETS = [
  {
    id: "cats_pixelart",
    label: "Коты pixelart",
    templates: ["tpl_plan_detective", "tpl_script_default", "tpl_img_pixelart", "tpl_anim_pixelart"],
  },
  {
    id: "knitted_family",
    label: "Вязаный 2D семейный",
    templates: ["tpl_plan_food", "tpl_script_default", "tpl_img_knitted", "tpl_hero_knitted"],
  },
  {
    id: "dark_noir",
    label: "Dark / trash polka",
    templates: ["tpl_script_king", "tpl_img_trash_polka"],
  },
];
